### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#51] opened 2020-06-15 14:30 UTC
When I want to change the message on the home page, by clicking on "", I am redirected to this page :
on the page :  https://chimitheque.inrae.fr/v/welcomeannounce

and I get this error message:
`perm type not found:all`

**Comment by tbellembois** [comment] 2020-06-15 14:32
duplicate of  #46
This is fixed in the trunk.

**Closed by tbellembois** 2020-06-15 14:32 UTC
